from .dominantdiminishedscale import DominantDiminishedScale as DiminishedBluesScale
from .hinduscale import HinduScale as AeolianDominantScale
from .hungarianscale import HungarianMinorScale as HungarianGypsyScale
